spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

ticket:
    price:
      adult: 25
      teen: 12
      child: 5
      discount:
        senior: 30
jwt:
    header: SDDD